services:
  frontend:
    image: nguyentho1907/oa-app:latest
    container_name: oa-frontend
    restart: unless-stopped
    ports:
      - "8088:80"

# Khi có backend sau này, thêm block mới ở đây, ví dụ:
# backend:
#   build: ./backend
#   container_name: oa-backend
#   restart: unless-stopped
#   ports:
#     - "5000:5000"
